"""acha ufala

Revision ID: 1401160f7048
Revises: 
Create Date: 2018-11-28 15:26:49.222212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1401160f7048'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_countries_image_url'), 'countries', ['image_url'], unique=False)
    op.add_column('parks', sa.Column('image_url', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_parks_image_url'), 'parks', ['image_url'], unique=False)
    op.add_column('wildlife', sa.Column('image_url', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_wildlife_image_url'), 'wildlife', ['image_url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wildlife_image_url'), table_name='wildlife')
    op.drop_column('wildlife', 'image_url')
    op.drop_index(op.f('ix_parks_image_url'), table_name='parks')
    op.drop_column('parks', 'image_url')
    op.drop_index(op.f('ix_countries_image_url'), table_name='countries')
    # ### end Alembic commands ###
