"""empty message

Revision ID: 19f56e12de28
Revises: 3e971be26a55
Create Date: 2019-01-18 11:41:39.555453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f56e12de28'
down_revision = '3e971be26a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'duration')
    # ### end Alembic commands ###
