"""rr

Revision ID: 32b73d26d4de
Revises: 102847718173
Create Date: 2018-11-29 15:26:19.316111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b73d26d4de'
down_revision = '102847718173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publishers', sa.Column('overal_ratings', sa.Integer(), nullable=True))
    op.add_column('publishers', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publishers', 'rating')
    op.drop_column('publishers', 'overal_ratings')
    # ### end Alembic commands ###
