"""rr

Revision ID: 486c7fcaeab0
Revises: 1401160f7048
Create Date: 2018-11-28 16:52:13.228042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486c7fcaeab0'
down_revision = '1401160f7048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('overal_ratings', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'rating')
    op.drop_column('listings', 'overal_ratings')
    # ### end Alembic commands ###
