"""empty message

Revision ID: 611c1978e4f0
Revises: 619cc19b9e01
Create Date: 2019-05-10 15:15:20.815683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611c1978e4f0'
down_revision = '619cc19b9e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_countries_overview', table_name='countries')
    op.add_column('publishers', sa.Column('operator_licence', sa.String(length=120), nullable=True))
    op.add_column('publishers', sa.Column('reg_certificate', sa.String(length=120), nullable=True))
    op.add_column('publishers', sa.Column('tax_registration', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publishers', 'tax_registration')
    op.drop_column('publishers', 'reg_certificate')
    op.drop_column('publishers', 'operator_licence')
    op.create_index('ix_countries_overview', 'countries', ['overview'], unique=False)
    # ### end Alembic commands ###
