"""empty message

Revision ID: 614bc7f85f43
Revises: d3cb8d372175
Create Date: 2019-03-07 14:49:02.284936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614bc7f85f43'
down_revision = 'd3cb8d372175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parks_description', table_name='parks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_parks_description', 'parks', ['description'], unique=False)
    # ### end Alembic commands ###
