"""empty message

Revision ID: 619cc19b9e01
Revises: d001daa47164
Create Date: 2019-03-07 14:51:33.579960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619cc19b9e01'
down_revision = 'd001daa47164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parks', sa.Column('description', sa.String(length=3070), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parks', 'description')
    # ### end Alembic commands ###
