"""empty message

Revision ID: 62c70a7e95d7
Revises: 19f56e12de28
Create Date: 2019-01-18 17:04:11.841141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c70a7e95d7'
down_revision = '19f56e12de28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('reason', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'reason')
    # ### end Alembic commands ###
