"""changes in publisher

Revision ID: 6592ba6c7add
Revises: 611c1978e4f0
Create Date: 2019-06-11 10:37:44.055768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6592ba6c7add'
down_revision = '611c1978e4f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publishers', sa.Column('association_membership', sa.String(length=120), nullable=True))
    op.add_column('publishers', sa.Column('physical_address', sa.String(length=120), nullable=True))
    op.add_column('publishers', sa.Column('postal_address', sa.String(length=120), nullable=True))
    op.drop_column('publishers', 'twitter')
    op.drop_column('publishers', 'instagram')
    op.drop_column('publishers', 'facebook')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publishers', sa.Column('facebook', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('publishers', sa.Column('instagram', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('publishers', sa.Column('twitter', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('publishers', 'postal_address')
    op.drop_column('publishers', 'physical_address')
    op.drop_column('publishers', 'association_membership')
    # ### end Alembic commands ###
