"""rr

Revision ID: 6c15c977e924
Revises: 6ee39daa62c2
Create Date: 2018-12-01 17:35:47.208228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c15c977e924'
down_revision = '6ee39daa62c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('value', mysql.VARCHAR(collation=u'utf8_bin', length=64), nullable=True))
    # ### end Alembic commands ###
