"""empty message

Revision ID: 6ee39daa62c2
Revises: dda35d845a0e
Create Date: 2018-11-30 15:21:54.795507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee39daa62c2'
down_revision = 'dda35d845a0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('social_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'social_id')
    # ### end Alembic commands ###
