"""empty message

Revision ID: 8b732cad07d7
Revises: 62c70a7e95d7
Create Date: 2019-01-18 17:40:00.989719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b732cad07d7'
down_revision = '62c70a7e95d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('reason', sa.String(length=300), nullable=True))
    op.drop_column('listings', 'reason')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('reason', mysql.VARCHAR(length=300), nullable=True))
    op.drop_column('bookings', 'reason')
    # ### end Alembic commands ###
