"""rr

Revision ID: a23aeee51b6a
Revises: a52bff89466c
Create Date: 2018-11-28 16:58:15.385710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23aeee51b6a'
down_revision = 'a52bff89466c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('overal_ratings', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'rating')
    op.drop_column('listings', 'overal_ratings')
    # ### end Alembic commands ###
