"""rr

Revision ID: a52bff89466c
Revises: 486c7fcaeab0
Create Date: 2018-11-28 16:57:22.818466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a52bff89466c'
down_revision = '486c7fcaeab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'overal_ratings')
    op.drop_column('listings', 'rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('overal_ratings', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
