"""empty message

Revision ID: be8b3c756a60
Revises: 
Create Date: 2019-01-22 09:41:27.050957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be8b3c756a60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('reason', sa.String(length=300), nullable=True))
    op.drop_index('ix_listings_duration', table_name='listings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_listings_duration', 'listings', ['duration'], unique=False)
    op.drop_column('bookings', 'reason')
    # ### end Alembic commands ###
