"""empty message

Revision ID: d001daa47164
Revises: 614bc7f85f43
Create Date: 2019-03-07 14:51:21.070626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd001daa47164'
down_revision = '614bc7f85f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parks', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parks', sa.Column('description', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
