"""empty message

Revision ID: d3cb8d372175
Revises: 0dd51e957f33
Create Date: 2019-03-07 13:15:34.495859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cb8d372175'
down_revision = '0dd51e957f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('description', sa.String(length=3070), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'description')
    # ### end Alembic commands ###
