"""rr

Revision ID: dda35d845a0e
Revises: 32b73d26d4de
Create Date: 2018-11-29 15:36:00.399602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda35d845a0e'
down_revision = '32b73d26d4de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'reviews_ibfk_3', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['publisher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(u'reviews_ibfk_3', 'reviews', 'publishers', ['publisher_id'], ['id'])
    # ### end Alembic commands ###
