"""empty message

Revision ID: e2e4bf507364
Revises: 79339818fe17
Create Date: 2019-08-06 11:09:42.373090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e4bf507364'
down_revision = '79339818fe17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publishers', sa.Column('bank_account', sa.String(length=120), nullable=True))
    op.add_column('publishers', sa.Column('bank_name', sa.String(length=120), nullable=True))
    op.add_column('publishers', sa.Column('swift_code', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publishers', 'swift_code')
    op.drop_column('publishers', 'bank_name')
    op.drop_column('publishers', 'bank_account')
    # ### end Alembic commands ###
