"""empty message

Revision ID: ee8e9517a901
Revises: 8b732cad07d7
Create Date: 2019-03-07 13:10:03.090259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee8e9517a901'
down_revision = '8b732cad07d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_countries_description', table_name='countries')
    op.drop_column('countries', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('description', mysql.VARCHAR(length=500), nullable=True))
    op.create_index('ix_countries_description', 'countries', ['description'], unique=False)
    # ### end Alembic commands ###
